<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Phrase;
class PhraseTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
              // Sample phrases and their video filenames
              $phrases = [
                ['phrase' => 'Magandang Araw', 'video_path' => 'signs/phrases/_Good Day_ in Filipino Sign Language.mp4'],
                ['phrase' => 'Good Day', 'video_path' => 'signs/phrases/_Good Day_ in Filipino Sign Language.mp4'],
                ['phrase' => 'Magandang Hatinggabi', 'video_path' => 'signs/phrases/_Good Midnight_ in Filipino Sign Language.mp4'],
                ['phrase' => 'Good Midgnight', 'video_path' => 'signs/phrases/_Good Midnight_ in Filipino Sign Language.mp4'],
                ['phrase' => 'Pilak', 'video_path' => 'signs/phrases/_Silver_ Variation 1 in Filipino Sign Language.mp4'],
                ['phrase' => 'Silver', 'video_path' => 'signs/phrases/_Silver_ Variation 1 in Filipino Sign Language.mp4'],
                ['phrase' => 'Ako ay nag-aaral', 'video_path' => 'signs/phrases/AKO AY NAG-AARAL NG FILIPINO SIGN LANGUAGE.mp4'],
                ['phrase' => 'I am studying', 'video_path' => 'signs/phrases/AKO AY NAG-AARAL NG FILIPINO SIGN LANGUAGE.mp4'],
                ['phrase' => 'Alin', 'video_path' => 'signs/phrases/Alin (Which) FSL.mp4'],
                ['phrase' => 'Ama', 'video_path' => 'signs/phrases/Ama, Papa, Tatay (father) FSL.mp4'],
                ['phrase' => 'Papa', 'video_path' => 'signs/phrases/Ama, Papa, Tatay (father) FSL.mp4'],
                ['phrase' => 'Tatay', 'video_path' => 'signs/phrases/Ama, Papa, Tatay (father) FSL.mp4'],
                ['phrase' => 'Father', 'video_path' => 'signs/phrases/Ama, Papa, Tatay (father) FSL.mp4'],
                ['phrase' => 'Annulment', 'video_path' => 'signs/phrases/Annulment in Filipino Sign Language.mp4'],
                ['phrase' => 'Ano', 'video_path' => 'signs/phrases/Ano (What) FSL.mp4'],
                ['phrase' => 'What', 'video_path' => 'signs/phrases/Ano (What) FSL.mp4'],
                ['phrase' => 'Mabuhay', 'video_path' => 'signs/phrases/Applause in Filipino Sign Language.mp4'],
                ['phrase' => 'Asawa', 'video_path' => 'signs/phrases/asawa (husband) .mp4'],
                ['phrase' => 'Husband', 'video_path' => 'signs/phrases/asawa (husband) .mp4'],
                ['phrase' => 'Asawa', 'video_path' => 'signs/phrases/Asawa (Wife) FSL.mp4'],
                ['phrase' => 'Wife', 'video_path' => 'signs/phrases/Asawa (Wife) FSL.mp4'],
                ['phrase' => 'Asul', 'video_path' => 'signs/phrases/Asul (Blue).mp4'],
                ['phrase' => 'Blue', 'video_path' => 'signs/phrases/Asul (Blue).mp4'],
                ['phrase' => 'Baby', 'video_path' => 'signs/phrases/Baby in Filipino Sign Language.mp4'],
                ['phrase' => 'Sanggol', 'video_path' => 'signs/phrases/Baby in Filipino Sign Language.mp4'],
                ['phrase' => 'Bakit', 'video_path' => 'signs/phrases/Bakit (Why) FSL.mp4'],
                ['phrase' => 'Why', 'video_path' => 'signs/phrases/Bakit (Why) FSL.mp4'],
                ['phrase' => 'Because', 'video_path' => 'signs/phrases/BECAUSE.mp4'],
                ['phrase' => 'Dahil', 'video_path' => 'signs/phrases/BECAUSE.mp4'],
                ['phrase' => 'Berde', 'video_path' => 'signs/phrases/Berde (Green) .mp4'],
                ['phrase' => 'Green', 'video_path' => 'signs/phrases/Berde (Green) .mp4'],
                ['phrase' => 'Boyfriend', 'video_path' => 'signs/phrases/Boyfriend Variation 1 in Filipino Sign Language.mp4'],
                ['phrase' => 'Kasintahan', 'video_path' => 'signs/phrases/Boyfriend Variation 1 in Filipino Sign Language.mp4'],
                ['phrase' => 'Kuya', 'video_path' => 'signs/phrases/Brother in Filipino Sign Language.mp4'],
                ['phrase' => 'Brother', 'video_path' => 'signs/phrases/Brother in Filipino Sign Language.mp4'],
                ['phrase' => 'Bulag', 'video_path' => 'signs/phrases/Bulag (Blind) FSL.mp4'],
                ['phrase' => 'Blind', 'video_path' => 'signs/phrases/Bulag (Blind) FSL.mp4'],
                ['phrase' => 'Bye', 'video_path' => 'signs/phrases/BYE PAALAM.mp4'],
                ['phrase' => 'Paalam', 'video_path' => 'signs/phrases/BYE PAALAM.mp4'],
                ['phrase' => 'Confidence', 'video_path' => 'signs/phrases/Confidence in Filipino Sign Language.mp4'],
                ['phrase' => 'Congratulations', 'video_path' => 'signs/phrases/Congratulations in Filipino Sign Language.mp4'],
                ['phrase' => 'Congrats', 'video_path' => 'signs/phrases/Congratulations in Filipino Sign Language.mp4'],
                ['phrase' => 'Cool', 'video_path' => 'signs/phrases/COOL.mp4'],
                ['phrase' => 'Crush', 'video_path' => 'signs/phrases/Crush in Filipino Sign Language.mp4'],
                ['phrase' => 'Date', 'video_path' => 'signs/phrases/Date Variation 1 in Filipino Sign Language.mp4'],
                ['phrase' => 'Yellow', 'video_path' => 'signs/phrases/Dilaw (Yellow).mp4'],
                ['phrase' => 'Dilaw', 'video_path' => 'signs/phrases/Dilaw (Yellow).mp4'],
                ['phrase' => 'Dito ako nakatira', 'video_path' => 'signs/phrases/DITO AKO NAKATIRA.mp4'],
                ['phrase' => 'This is where I live', 'video_path' => 'signs/phrases/DITO AKO NAKATIRA.mp4'],
                ['phrase' => 'Edukasyon', 'video_path' => 'signs/phrases/Edukasyon (Education).mp4'],
                ['phrase' => 'Education', 'video_path' => 'signs/phrases/Edukasyon (Education).mp4'],
                ['phrase' => 'Pamilya', 'video_path' => 'signs/phrases/Family members in Filipino Sign Language.mp4'],
                ['phrase' => 'Family', 'video_path' => 'signs/phrases/Family members in Filipino Sign Language.mp4'],
                ['phrase' => 'Filipino Sign Language', 'video_path' => 'signs/phrases/Filipino Sign Language Variation 1 in Filipino Sign Language.mp4'],
                ['phrase' => 'From', 'video_path' => 'signs/phrases/FROM.mp4'],
                ['phrase' => 'Galing ako sa', 'video_path' => 'signs/phrases/GALING AKO SA.mp4'],
                ['phrase' => 'Ginto', 'video_path' => 'signs/phrases/Ginto (gold).mp4'],
                ['phrase' => 'Gold', 'video_path' => 'signs/phrases/Ginto (gold).mp4'],
                ['phrase' => 'Girlfriend', 'video_path' => 'signs/phrases/Girlfriend Variation 2 in Filipino Sign Language.mp4'],
                ['phrase' => 'Kasintahan', 'video_path' => 'signs/phrases/Girlfriend Variation 2 in Filipino Sign Language.mp4'],
                ['phrase' => 'Lolo', 'video_path' => 'signs/phrases/Grandfather in Filipino Sign Language.mp4'],
                ['phrase' => 'Grandfather', 'video_path' => 'signs/phrases/Grandfather in Filipino Sign Language.mp4'],
                ['phrase' => 'Lola', 'video_path' => 'signs/phrases/Grandmother in Filipino Sign Language.mp4'],
                ['phrase' => 'Grandmother', 'video_path' => 'signs/phrases/Grandmother in Filipino Sign Language.mp4'],
                ['phrase' => 'Guard', 'video_path' => 'signs/phrases/Guard Variation 2 in Filipino Sign Language.mp4'],
                ['phrase' => 'Gwardiya', 'video_path' => 'signs/phrases/Guard Variation 2 in Filipino Sign Language.mp4'],
                ['phrase' => 'Gwardya', 'video_path' => 'signs/phrases/Guard Variation 2 in Filipino Sign Language.mp4'],
                ['phrase' => 'Guro', 'video_path' => 'signs/phrases/Guro (Teacher) FSL .mp4'],
                ['phrase' => 'Teacher', 'video_path' => 'signs/phrases/Guro (Teacher) FSL .mp4'],
                ['phrase' => 'Gymnasium', 'video_path' => 'signs/phrases/Gymnasium in Filipino Sign Language.mp4'],
                ['phrase' => 'Maligayang Kaarawan', 'video_path' => 'signs/phrases/Happy Birthday ALL in Filipino Sign Language.mp4'],
                ['phrase' => 'Happy Birthday', 'video_path' => 'signs/phrases/Happy Birthday ALL in Filipino Sign Language.mp4'],
                ['phrase' => 'Happy new year', 'video_path' => 'signs/phrases/Happy New Year in Filipino Sign Language.mp4'],
                ['phrase' => 'Maligayang Bagong Taon', 'video_path' => 'signs/phrases/Happy New Year in Filipino Sign Language.mp4'],
                ['phrase' => 'Happy Valentines Day', 'video_path' => 'signs/phrases/Happy Valentine_s Day in Filipino Sign Language.mp4'],
                ['phrase' => 'he', 'video_path' => 'signs/phrases/HE SHE.mp4'],
                ['phrase' => 'she', 'video_path' => 'signs/phrases/HE SHE.mp4'],
                ['phrase' => 'heto', 'video_path' => 'signs/phrases/here.mp4'],
                ['phrase' => 'here', 'video_path' => 'signs/phrases/here.mp4'],
                ['phrase' => 'eto', 'video_path' => 'signs/phrases/here.mp4'],
                ['phrase' => 'Hikayatin', 'video_path' => 'signs/phrases/Hikayatin (Encourage).mp4'],
                ['phrase' => 'Encourage', 'video_path' => 'signs/phrases/Hikayatin (Encourage).mp4'],
                ['phrase' => 'His', 'video_path' => 'signs/phrases/HIS HER.mp4'],
                ['phrase' => 'Her', 'video_path' => 'signs/phrases/HIS HER.mp4'],
                ['phrase' => 'History', 'video_path' => 'signs/phrases/History in Filipino Sign Language.mp4'],
                ['phrase' => 'Kasaysayan', 'video_path' => 'signs/phrases/History in Filipino Sign Language.mp4'],
                ['phrase' => 'How Much', 'video_path' => 'signs/phrases/HOW MUCH.mp4'],
                ['phrase' => 'Magkano', 'video_path' => 'signs/phrases/HOW MUCH.mp4'],
                ['phrase' => 'Huminto sa Pag-aaral', 'video_path' => 'signs/phrases/Huminto sa pag-aaral FSL.mp4'],
                ['phrase' => 'Huminto sa pag aaral', 'video_path' => 'signs/phrases/Huminto sa pag-aaral FSL.mp4'],
                ['phrase' => 'Stopped School', 'video_path' => 'signs/phrases/Huminto sa pag-aaral FSL.mp4'],
                ['phrase' => 'Hindi ko alam', 'video_path' => 'signs/phrases/I DON_T KNOW.mp4'],
                ['phrase' => 'Di ko alam', 'video_path' => 'signs/phrases/I DON_T KNOW.mp4'],
                ['phrase' => 'I dont know', 'video_path' => 'signs/phrases/I DON_T KNOW.mp4'],
                ['phrase' => 'I hate you', 'video_path' => 'signs/phrases/I hate you Variation 1 in Filipino Sign Language.mp4'],
                ['phrase' => 'I like you', 'video_path' => 'signs/phrases/I like you in Filipino Sign Language.mp4'],
                ['phrase' => 'Gusto Kita', 'video_path' => 'signs/phrases/I want you in Filipino Sign Language.mp4'],
                ['phrase' => 'I miss you', 'video_path' => 'signs/phrases/I miss you in Filipino Sign Language.mp4'],
                ['phrase' => 'Miss na kita', 'video_path' => 'signs/phrases/I miss you in Filipino Sign Language.mp4'],
                ['phrase' => 'I really love you', 'video_path' => 'signs/phrases/I really love you Variation 2 in Filipino Sign Language.mp4'],
                ['phrase' => 'Mahal na mahal kita', 'video_path' => 'signs/phrases/I really love you Variation 2 in Filipino Sign Language.mp4'],
                ['phrase' => 'I want you', 'video_path' => 'signs/phrases/I want you in Filipino Sign Language.mp4'],
                ['phrase' => 'Ilan?', 'video_path' => 'signs/phrases/Ilan (How Many) FSL.mp4'],
                ['phrase' => 'How many?', 'video_path' => 'signs/phrases/Ilan (How Many) FSL.mp4'],
                ['phrase' => 'Ilan', 'video_path' => 'signs/phrases/Ilan (How Many) FSL.mp4'],
                ['phrase' => 'How many', 'video_path' => 'signs/phrases/Ilan (How Many) FSL.mp4'],
                ['phrase' => 'Independent', 'video_path' => 'signs/phrases/Independent in Filipino Sign Language.mp4'],
                ['phrase' => 'Inspired', 'video_path' => 'signs/phrases/Inspired in Filipino Sign Language.mp4'],
                ['phrase' => 'Iskolar', 'video_path' => 'signs/phrases/iskolar (Scholar) FSL.mp4'],
                ['phrase' => 'Scholar', 'video_path' => 'signs/phrases/iskolar (Scholar) FSL.mp4'],
                ['phrase' => 'Itim', 'video_path' => 'signs/phrases/Itim (Black).mp4'],
                ['phrase' => 'Black', 'video_path' => 'signs/phrases/Itim (Black).mp4'],
                ['phrase' => 'Kahel', 'video_path' => 'signs/phrases/kahel (orange).mp4'],
                ['phrase' => 'Orange', 'video_path' => 'signs/phrases/kahel (orange).mp4'],
                ['phrase' => 'Kaibigan', 'video_path' => 'signs/phrases/Kaibigan (bestfriend).mp4'],
                ['phrase' => 'Friend', 'video_path' => 'signs/phrases/Kaibigan (bestfriend).mp4'],
                ['phrase' => 'Kaibigan', 'video_path' => 'signs/phrases/Kaibigan (Friend) FSL.mp4'],
                ['phrase' => 'Bestfriend', 'video_path' => 'signs/phrases/Kaibigan (bestfriend).mp4'],
                ['phrase' => 'Best friend', 'video_path' => 'signs/phrases/Kaibigan (bestfriend).mp4'],
                ['phrase' => 'Kailan', 'video_path' => 'signs/phrases/Kailan (When) FSL.mp4'],
                ['phrase' => 'Kelan', 'video_path' => 'signs/phrases/Kailan (When) FSL.mp4'],
                ['phrase' => 'Kaylan', 'video_path' => 'signs/phrases/Kailan (When) FSL.mp4'],
                ['phrase' => 'When', 'video_path' => 'signs/phrases/Kailan (When) FSL.mp4'],
                ['phrase' => 'Kamag-aral', 'video_path' => 'signs/phrases/kamag-aral o kaklase (classmate) FSL.mp4'],
                ['phrase' => 'Kamagaral', 'video_path' => 'signs/phrases/kamag-aral o kaklase (classmate) FSL.mp4'],
                ['phrase' => 'Kamag aral', 'video_path' => 'signs/phrases/kamag-aral o kaklase (classmate) FSL.mp4'],
                ['phrase' => 'Classmate', 'video_path' => 'signs/phrases/kamag-aral o kaklase (classmate) FSL.mp4'],
                ['phrase' => 'Kaklase', 'video_path' => 'signs/phrases/kamag-aral o kaklase (classmate) FSL.mp4'],
                ['phrase' => 'Kanino', 'video_path' => 'signs/phrases/Kanino (Whom) FSL.mp4'],
                ['phrase' => 'Whom', 'video_path' => 'signs/phrases/Kanino (Whom) FSL.mp4'],
                ['phrase' => 'Kapansanan', 'video_path' => 'signs/phrases/Kapansanan FSL.mp4'],
                ['phrase' => 'Disability', 'video_path' => 'signs/phrases/Kapansanan FSL.mp4'],
                ['phrase' => 'Karapatan', 'video_path' => 'signs/phrases/karapatan (rights).mp4'],
                ['phrase' => 'Rights', 'video_path' => 'signs/phrases/karapatan (rights).mp4'],
                ['phrase' => 'Kayumanggi', 'video_path' => 'signs/phrases/Kayumanggi (Brown).mp4'],
                ['phrase' => 'Brown', 'video_path' => 'signs/phrases/Kayumanggi (Brown).mp4'],
                ['phrase' => 'Kilig', 'video_path' => 'signs/phrases/Kilig FSL.mp4'],
                ['phrase' => 'Klase', 'video_path' => 'signs/phrases/Klase (Class).mp4'],
                ['phrase' => 'Class', 'video_path' => 'signs/phrases/Klase (Class).mp4'],
                ['phrase' => 'Kulay abo', 'video_path' => 'signs/phrases/kulay abo (gray).mp4'],
                ['phrase' => 'Abo', 'video_path' => 'signs/phrases/kulay abo (gray).mp4'],
                ['phrase' => 'Ash', 'video_path' => 'signs/phrases/kulay abo (gray).mp4'],
                ['phrase' => 'Gray', 'video_path' => 'signs/phrases/kulay abo (gray).mp4'],
                ['phrase' => 'Kulay', 'video_path' => 'signs/phrases/Kulay.mp4'],
                ['phrase' => 'Color', 'video_path' => 'signs/phrases/Kulay.mp4'],
                ['phrase' => 'Lila', 'video_path' => 'signs/phrases/Lila (Violet).mp4'],
                ['phrase' => 'Violet', 'video_path' => 'signs/phrases/Lila (Violet).mp4'],
                ['phrase' => 'Lipat', 'video_path' => 'signs/phrases/Lipat, Paglipat (Transfer) FSL.mp4'],
                ['phrase' => 'Paglipat', 'video_path' => 'signs/phrases/Lipat, Paglipat (Transfer) FSL.mp4'],
                ['phrase' => 'Transfer', 'video_path' => 'signs/phrases/Lipat, Paglipat (Transfer) FSL.mp4'],
                ['phrase' => 'Live', 'video_path' => 'signs/phrases/live.mp4'],
                ['phrase' => 'Mabuhay', 'video_path' => 'signs/phrases/Mabuhay fsl.mp4'],
                ['phrase' => 'Mag-aaral', 'video_path' => 'signs/phrases/Mag-aaral o Estudyante (Student) FSL.mp4'],
                ['phrase' => 'Student', 'video_path' => 'signs/phrases/Mag-aaral o Estudyante (Student) FSL.mp4'],
                ['phrase' => 'Estudyante', 'video_path' => 'signs/phrases/Mag-aaral o Estudyante (Student) FSL.mp4'],
                ['phrase' => 'Studyante', 'video_path' => 'signs/phrases/Mag-aaral o Estudyante (Student) FSL.mp4'],
                ['phrase' => 'Magandang Gabi', 'video_path' => 'signs/phrases/Magandang Gabi (Good Evening) FSL .mp4'],
                ['phrase' => 'Good evening', 'video_path' => 'signs/phrases/Magandang Gabi (Good Evening) FSL .mp4'],
                ['phrase' => 'Magandang Gabi', 'video_path' => 'signs/phrases/Magandang Gabi (Goodnight) FSL.mp4'],
                ['phrase' => 'Good Night', 'video_path' => 'signs/phrases/Magandang Gabi (Goodnight) FSL.mp4'],
                ['phrase' => 'Magandang Hapon', 'video_path' => 'signs/phrases/Magandang Hapon FSL.mp4'],
                ['phrase' => 'Good afternoon', 'video_path' => 'signs/phrases/Magandang Hapon FSL.mp4'],
                ['phrase' => 'Magandang Tanghali', 'video_path' => 'signs/phrases/Magandang Tanghali FSL.mp4'],
                ['phrase' => 'Good Noon', 'video_path' => 'signs/phrases/Magandang Tanghali FSL.mp4'],
                ['phrase' => 'Magandang Umaga', 'video_path' => 'signs/phrases/Magandang Umaga FSL.mp4'],
                ['phrase' => 'Good Morning', 'video_path' => 'signs/phrases/Magandang Umaga FSL.mp4'],
                ['phrase' => 'Magkasama', 'video_path' => 'signs/phrases/Magkasama (Together) FSL.mp4'],
                ['phrase' => 'Together', 'video_path' => 'signs/phrases/Magkasama (Together) FSL.mp4'],
                ['phrase' => 'Mahal Kita', 'video_path' => 'signs/phrases/mahal kita (i love you).mp4'],
                ['phrase' => 'I love you', 'video_path' => 'signs/phrases/mahal kita (i love you).mp4'],
                ['phrase' => 'Malakas', 'video_path' => 'signs/phrases/malakas (strong) .mp4'],
                ['phrase' => 'Strong', 'video_path' => 'signs/phrases/malakas (strong) .mp4'],
                ['phrase' => 'Matapang', 'video_path' => 'signs/phrases/Matapang (Brave).mp4'],
                ['phrase' => 'Brave', 'video_path' => 'signs/phrases/Matapang (Brave).mp4'],
                ['phrase' => 'May crush ako sayo', 'video_path' => 'signs/phrases/May crush ako sa_yo (I have a crush on you) FSL.mp4'],
                ['phrase' => 'I have a crush on you', 'video_path' => 'signs/phrases/May crush ako sa_yo (I have a crush on you) FSL.mp4'],
                ['phrase' => 'Maybe', 'video_path' => 'signs/phrases/MAYBE.mp4'],
                ['phrase' => 'Baka', 'video_path' => 'signs/phrases/MAYBE.mp4'],
                ['phrase' => 'Me', 'video_path' => 'signs/phrases/ME I.mp4'],
                ['phrase' => 'I', 'video_path' => 'signs/phrases/ME I.mp4'],
                ['phrase' => 'Ako', 'video_path' => 'signs/phrases/ME I.mp4'],
                ['phrase' => 'Merry Christmas', 'video_path' => 'signs/phrases/Merry Christmas in Filipino Sign Language.mp4'],
                ['phrase' => 'Maligayang Pasko', 'video_path' => 'signs/phrases/Merry Christmas in Filipino Sign Language.mp4'],
                ['phrase' => 'Mine', 'video_path' => 'signs/phrases/MINE.mp4'],
                ['phrase' => 'Sakin', 'video_path' => 'signs/phrases/MINE.mp4'],
                ['phrase' => 'Nanay', 'video_path' => 'signs/phrases/Nanay, Mama, Ina (Mother) FSL.mp4'],
                ['phrase' => 'Mama', 'video_path' => 'signs/phrases/Nanay, Mama, Ina (Mother) FSL.mp4'],
                ['phrase' => 'Ina', 'video_path' => 'signs/phrases/Nanay, Mama, Ina (Mother) FSL.mp4'],
                ['phrase' => 'Mother', 'video_path' => 'signs/phrases/Nanay, Mama, Ina (Mother) FSL.mp4'],
                ['phrase' => 'No problem', 'video_path' => 'signs/phrases/NO PROBLEM.mp4'],
                ['phrase' => 'Walang problema', 'video_path' => 'signs/phrases/NO PROBLEM.mp4'],
                ['phrase' => 'Walang anuman', 'video_path' => 'signs/phrases/NO PROBLEM.mp4'],
                ['phrase' => 'No', 'video_path' => 'signs/phrases/NO.mp4'],
                ['phrase' => 'Hindi', 'video_path' => 'signs/phrases/NO.mp4'],
                ['phrase' => 'Not sure', 'video_path' => 'signs/phrases/NOT SURE.mp4'],
                ['phrase' => 'Hindi sigurado', 'video_path' => 'signs/phrases/NOT SURE.mp4'],
                ['phrase' => 'Ngayon', 'video_path' => 'signs/phrases/NOW.mp4'],
                ['phrase' => 'Now', 'video_path' => 'signs/phrases/NOW.mp4'],
                ['phrase' => 'Nowhere', 'video_path' => 'signs/phrases/NOWHERE.mp4'],
                ['phrase' => 'Office', 'video_path' => 'signs/phrases/Office in Filipino Sign Language.mp4'],
                ['phrase' => 'Opisina', 'video_path' => 'signs/phrases/Office in Filipino Sign Language.mp4'],
                ['phrase' => 'Oh I see', 'video_path' => 'signs/phrases/OH I SEE.mp4'],
                ['phrase' => 'Okay', 'video_path' => 'signs/phrases/OKAY.mp4'],
                ['phrase' => 'Our', 'video_path' => 'signs/phrases/OUR.mp4'],
                ['phrase' => 'Over there', 'video_path' => 'signs/phrases/OVER THERE.mp4'],
                ['phrase' => 'Paalam', 'video_path' => 'signs/phrases/Paalam FSL.mp4'],
                ['phrase' => 'Goodbye', 'video_path' => 'signs/phrases/Paalam FSL.mp4'],
                ['phrase' => 'Good bye', 'video_path' => 'signs/phrases/Paalam FSL.mp4'],
                ['phrase' => 'How', 'video_path' => 'signs/phrases/Paano (How) FSL.mp4'],
                ['phrase' => 'Paano', 'video_path' => 'signs/phrases/Paano (How) FSL.mp4'],
                ['phrase' => 'Paaralan', 'video_path' => 'signs/phrases/Paaralan (School) FSL.mp4'],
                ['phrase' => 'School', 'video_path' => 'signs/phrases/Paaralan (School) FSL.mp4'],
                ['phrase' => 'Pagbati', 'video_path' => 'signs/phrases/Pagbati, Binabati kita (Congratulations) FSL.mp4'],
                ['phrase' => 'Binabati Kita', 'video_path' => 'signs/phrases/Pagbati, Binabati kita (Congratulations) FSL.mp4'],
                ['phrase' => 'Congratulation', 'video_path' => 'signs/phrases/Pagbati, Binabati kita (Congratulations) FSL.mp4'],
                ['phrase' => 'Congrats', 'video_path' => 'signs/phrases/Pagbati, Binabati kita (Congratulations) FSL.mp4'],
                ['phrase' => 'Pagdiwang', 'video_path' => 'signs/phrases/pagdiwang, pagdiriwang (celebration).mp4'],
                ['phrase' => 'Pagdiriwang', 'video_path' => 'signs/phrases/pagdiwang, pagdiriwang (celebration).mp4'],
                ['phrase' => 'Celebration', 'video_path' => 'signs/phrases/pagdiwang, pagdiriwang (celebration).mp4'],
                ['phrase' => 'Pag ibig', 'video_path' => 'signs/phrases/Pag-ibig, pagmamahal, (Love) .mp4'],
                ['phrase' => 'Pag-ibig', 'video_path' => 'signs/phrases/Pag-ibig, pagmamahal, (Love) .mp4'],
                ['phrase' => 'Pagmamahal', 'video_path' => 'signs/phrases/Pag-ibig, pagmamahal, (Love) .mp4'],
                ['phrase' => 'Love', 'video_path' => 'signs/phrases/Pag-ibig, pagmamahal, (Love) .mp4'],
                ['phrase' => 'Pagkakapantay-pantay', 'video_path' => 'signs/phrases/pagkakapantay-pantay (Equality) .mp4'],
                ['phrase' => 'Pagkakapantay pantay', 'video_path' => 'signs/phrases/pagkakapantay-pantay (Equality) .mp4'],
                ['phrase' => 'Equality', 'video_path' => 'signs/phrases/pagkakapantay-pantay (Equality) .mp4'],
                ['phrase' => 'Pagtapos', 'video_path' => 'signs/phrases/Pagtatapos (Graduation).mp4'],
                ['phrase' => 'Graduation', 'video_path' => 'signs/phrases/Pagtatapos (Graduation).mp4'],
                ['phrase' => 'Palakpak', 'video_path' => 'signs/phrases/Palakpak (Applause).mp4'],
                ['phrase' => 'Applause', 'video_path' => 'signs/phrases/Palakpak (Applause).mp4'],
                ['phrase' => 'Partner', 'video_path' => 'signs/phrases/Partner in Filipino Sign Language.mp4'],
                ['phrase' => 'Punong-guro', 'video_path' => 'signs/phrases/Principal in Filipino Sign Language.mp4'],
                ['phrase' => 'Punong guro', 'video_path' => 'signs/phrases/Principal in Filipino Sign Language.mp4'],
                ['phrase' => 'Principal', 'video_path' => 'signs/phrases/Principal in Filipino Sign Language.mp4'],
                ['phrase' => 'Principals Office', 'video_path' => 'signs/phrases/Principal_s Office in Filipino Sign Language.mp4'],
                ['phrase' => 'Principal Office', 'video_path' => 'signs/phrases/Principal_s Office in Filipino Sign Language.mp4'],
                ['phrase' => 'Tanggapan ng Punong-guro', 'video_path' => 'signs/phrases/Principal_s Office in Filipino Sign Language.mp4'],
                ['phrase' => 'Tanggapan ng punong guro', 'video_path' => 'signs/phrases/Principal_s Office in Filipino Sign Language.mp4'],
                ['phrase' => 'Problem', 'video_path' => 'signs/phrases/PROBLEM.mp4'],
                ['phrase' => 'Problema', 'video_path' => 'signs/phrases/PROBLEM.mp4'],
                ['phrase' => 'Progressive Pronoun', 'video_path' => 'signs/phrases/PROGRESSIVE PRONOUN.mp4'],
                ['phrase' => 'Pronoun', 'video_path' => 'signs/phrases/PRONOUNS.mp4'],
                ['phrase' => 'Pula', 'video_path' => 'signs/phrases/Pula (Red).mp4'],
                ['phrase' => 'Red', 'video_path' => 'signs/phrases/Pula (Red).mp4'],
                ['phrase' => 'Puti', 'video_path' => 'signs/phrases/Puti (White).mp4'],
                ['phrase' => 'White', 'video_path' => 'signs/phrases/Puti (White).mp4'],
                ['phrase' => 'Respeto', 'video_path' => 'signs/phrases/Respeto (Respect) .mp4'],
                ['phrase' => 'Respect', 'video_path' => 'signs/phrases/Respeto (Respect) .mp4'],
                ['phrase' => 'Kulay Rosas', 'video_path' => 'signs/phrases/Rosas (Pink).mp4'],
                ['phrase' => 'Pink', 'video_path' => 'signs/phrases/Rosas (Pink).mp4'],
                ['phrase' => 'Rosas', 'video_path' => 'signs/phrases/Rosas (Pink).mp4'],
                ['phrase' => 'Saan', 'video_path' => 'signs/phrases/Saan (Where) FSL.mp4'],
                ['phrase' => 'Where', 'video_path' => 'signs/phrases/Saan (Where) FSL.mp4'],
                ['phrase' => 'Salamat', 'video_path' => 'signs/phrases/Salamat (Thank You) FSL.mp4'],
                ['phrase' => 'Thank You', 'video_path' => 'signs/phrases/Salamat (Thank You) FSL.mp4'],
                ['phrase' => 'Self Love', 'video_path' => 'signs/phrases/Self love Variation 2 in Filipino Sign Language.mp4'],
                ['phrase' => 'Self-Love', 'video_path' => 'signs/phrases/Self love Variation 2 in Filipino Sign Language.mp4'],
                ['phrase' => 'Signing Words', 'video_path' => 'signs/phrases/SIGNING WORDS.mp4'],
                ['phrase' => 'Single', 'video_path' => 'signs/phrases/Single in Filipino Sign Language.mp4'],
                ['phrase' => 'Sino', 'video_path' => 'signs/phrases/Sino (Who) FSL.mp4'],
                ['phrase' => 'Who', 'video_path' => 'signs/phrases/Sino (Who) FSL.mp4'],
                ['phrase' => 'Sister', 'video_path' => 'signs/phrases/Sister in Filipino Sign Language.mp4'],
                ['phrase' => 'Ate', 'video_path' => 'signs/phrases/Sister in Filipino Sign Language.mp4'],
                ['phrase' => 'Somewhere', 'video_path' => 'signs/phrases/SOMEWHERE.mp4'],
                ['phrase' => 'Kung saan', 'video_path' => 'signs/phrases/SOMEWHERE.mp4'],
                ['phrase' => 'Struggle', 'video_path' => 'signs/phrases/Struggle Variation 1 in Filipino Sign Language.mp4'],
                ['phrase' => 'Suporta', 'video_path' => 'signs/phrases/suporta (support) FSL.mp4'],
                ['phrase' => 'Supporta', 'video_path' => 'signs/phrases/suporta (support) FSL.mp4'],
                ['phrase' => 'Support', 'video_path' => 'signs/phrases/suporta (support) FSL.mp4'],
                ['phrase' => 'Sure', 'video_path' => 'signs/phrases/SURE.mp4'],
                ['phrase' => 'Sige', 'video_path' => 'signs/phrases/SURE.mp4'],
                ['phrase' => 'Sweetheart', 'video_path' => 'signs/phrases/Sweetheart in Filipino Sign Language.mp4'],
                ['phrase' => 'Sweet heart', 'video_path' => 'signs/phrases/Sweetheart in Filipino Sign Language.mp4'],
                ['phrase' => 'Taga saan ka?', 'video_path' => 'signs/phrases/TAGA SAAN KA.mp4'],
                ['phrase' => 'Where are you from?', 'video_path' => 'signs/phrases/TAGA SAAN KA.mp4'],
                ['phrase' => 'Taga saan ka', 'video_path' => 'signs/phrases/TAGA SAAN KA.mp4'],
                ['phrase' => 'Where are you from', 'video_path' => 'signs/phrases/TAGA SAAN KA.mp4'],
                ['phrase' => 'Theatre', 'video_path' => 'signs/phrases/Theater in Filipino Sign Language.mp4'],
                ['phrase' => 'Teatro', 'video_path' => 'signs/phrases/Theater in Filipino Sign Language.mp4'],
                ['phrase' => 'Their', 'video_path' => 'signs/phrases/THEIR.mp4'],
                ['phrase' => 'Them', 'video_path' => 'signs/phrases/THEM.mp4'],
                ['phrase' => 'Undas', 'video_path' => 'signs/phrases/Undas Variation 1 in Filipino Sign Language.mp4'],
                ['phrase' => 'Unibersidad', 'video_path' => 'signs/phrases/Unibersidad (University) FSL.mp4'],
                ['phrase' => 'University', 'video_path' => 'signs/phrases/Unibersidad (University) FSL.mp4'],
                ['phrase' => 'Wait', 'video_path' => 'signs/phrases/WAIT.mp4'],
                ['phrase' => 'Teka', 'video_path' => 'signs/phrases/WAIT.mp4'],
                ['phrase' => 'Welcome', 'video_path' => 'signs/phrases/Walang anuman (welcome) fsl.mp4'],
                ['phrase' => 'Walang anuman', 'video_path' => 'signs/phrases/Walang anuman (welcome) fsl.mp4'],
                ['phrase' => 'We', 'video_path' => 'signs/phrases/WE.mp4'],
                ['phrase' => 'Whatever', 'video_path' => 'signs/phrases/WHATEVER.mp4'],
                ['phrase' => 'Which', 'video_path' => 'signs/phrases/WHICH.mp4'],
                ['phrase' => 'Wow', 'video_path' => 'signs/phrases/WOW.mp4'],
                ['phrase' => 'Yes', 'video_path' => 'signs/phrases/YES.mp4'],
                ['phrase' => 'Oo', 'video_path' => 'signs/phrases/YES.mp4'],
                ['phrase' => 'You', 'video_path' => 'signs/phrases/YOU.mp4'],
                ['phrase' => 'Ikaw', 'video_path' => 'signs/phrases/YOU.mp4'],
                ['phrase' => 'Your', 'video_path' => 'signs/phrases/YOUR.mp4'],


                // Add more phrases as needed
            ];

            // Insert phrases into the database
            foreach ($phrases as $phrase) {
                Phrase::create([
                    'phrase' => $phrase['phrase'],
                    'video_path' => $phrase['video_path'],
                ]);
            }
    }
}
