<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Phrase;
class PhraseTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
              // Sample phrases and their video filenames
              $phrases = [
                ['phrase' => 'Magandang Araw', 'video_path' => 'signs/phrases/_Good Day_ in Filipino Sign Language.mp4'],
                ['phrase' => 'Good Day', 'video_path' => 'signs/phrases/_Good Day_ in Filipino Sign Language.mp4'],
                ['phrase' => 'Magandang Hatinggabi', 'video_path' => 'signs/phrases/_Good Midnight_ in Filipino Sign Language.mp4'],
                ['phrase' => 'Good Midgnight', 'video_path' => 'signs/phrases/_Good Midnight_ in Filipino Sign Language.mp4'],
                ['phrase' => 'Pilak', 'video_path' => 'signs/phrases/_Silver_ Variation 1 in Filipino Sign Language.mp4'],
                ['phrase' => 'Silver', 'video_path' => 'signs/phrases/_Silver_ Variation 1 in Filipino Sign Language.mp4'],
                ['phrase' => 'Ako ay nag-aaral', 'video_path' => 'signs/phrases/AKO AY NAG-AARAL NG FILIPINO SIGN LANGUAGE.mp4'],
                ['phrase' => 'I am studying', 'video_path' => 'signs/phrases/AKO AY NAG-AARAL NG FILIPINO SIGN LANGUAGE.mp4'],
                ['phrase' => 'Alin', 'video_path' => 'signs/phrases/Alin (Which) FSL.mp4'],
                ['phrase' => 'Ama', 'video_path' => 'signs/phrases/Ama, Papa, Tatay (father) FSL.mp4'],
                ['phrase' => 'Papa', 'video_path' => 'signs/phrases/Ama, Papa, Tatay (father) FSL.mp4'],
                ['phrase' => 'Tatay', 'video_path' => 'signs/phrases/Ama, Papa, Tatay (father) FSL.mp4'],
                ['phrase' => 'Father', 'video_path' => 'signs/phrases/Ama, Papa, Tatay (father) FSL.mp4'],
                ['phrase' => 'Annulment', 'video_path' => 'signs/phrases/Annulment in Filipino Sign Language.mp4'],
                ['phrase' => 'Ano', 'video_path' => 'signs/phrases/Ano (What) FSL.mp4'],
                ['phrase' => 'What', 'video_path' => 'signs/phrases/Ano (What) FSL.mp4'],
                ['phrase' => 'Mabuhay', 'video_path' => 'signs/phrases/Applause in Filipino Sign Language.mp4'],
                ['phrase' => 'Asawa', 'video_path' => 'signs/phrases/asawa (husband) .mp4'],
                ['phrase' => 'Husband', 'video_path' => 'signs/phrases/asawa (husband) .mp4'],
                ['phrase' => 'Asawa', 'video_path' => 'signs/phrases/Asawa (Wife) FSL.mp4'],
                ['phrase' => 'Wife', 'video_path' => 'signs/phrases/Asawa (Wife) FSL.mp4'],
                ['phrase' => 'Asul', 'video_path' => 'signs/phrases/Asul (Blue).mp4'],
                ['phrase' => 'Blue', 'video_path' => 'signs/phrases/Asul (Blue).mp4'],
                ['phrase' => 'Baby', 'video_path' => 'signs/phrases/Baby in Filipino Sign Language.mp4'],
                ['phrase' => 'Sanggol', 'video_path' => 'signs/phrases/Baby in Filipino Sign Language.mp4'],
                ['phrase' => 'Bakit', 'video_path' => 'signs/phrases/Bakit (Why) FSL.mp4'],
                ['phrase' => 'Why', 'video_path' => 'signs/phrases/Bakit (Why) FSL.mp4'],
                ['phrase' => 'Because', 'video_path' => 'signs/phrases/BECAUSE.mp4'],
                ['phrase' => 'Dahil', 'video_path' => 'signs/phrases/BECAUSE.mp4'],
                ['phrase' => 'Berde', 'video_path' => 'signs/phrases/Berde (Green) .mp4'],
                ['phrase' => 'Green', 'video_path' => 'signs/phrases/Berde (Green) .mp4'],
                ['phrase' => 'Boyfriend', 'video_path' => 'signs/phrases/Boyfriend Variation 1 in Filipino Sign Language.mp4'],
                ['phrase' => 'Kasintahan', 'video_path' => 'signs/phrases/Boyfriend Variation 1 in Filipino Sign Language.mp4'],
                ['phrase' => 'Kuya', 'video_path' => 'signs/phrases/Brother in Filipino Sign Language.mp4'],
                ['phrase' => 'Brother', 'video_path' => 'signs/phrases/Brother in Filipino Sign Language.mp4'],
                ['phrase' => 'Bulag', 'video_path' => 'signs/phrases/Bulag (Blind) FSL.mp4'],
                ['phrase' => 'Blind', 'video_path' => 'signs/phrases/Bulag (Blind) FSL.mp4'],
                ['phrase' => 'Bye', 'video_path' => 'signs/phrases/BYE PAALAM.mp4'],
                ['phrase' => 'Paalam', 'video_path' => 'signs/phrases/BYE PAALAM.mp4'],
                ['phrase' => 'Confidence', 'video_path' => 'signs/phrases/Confidence in Filipino Sign Language.mp4'],
                ['phrase' => 'Congratulations', 'video_path' => 'signs/phrases/Congratulations in Filipino Sign Language.mp4'],
                ['phrase' => 'Congrats', 'video_path' => 'signs/phrases/Congratulations in Filipino Sign Language.mp4'],
                ['phrase' => 'Cool', 'video_path' => 'signs/phrases/COOL.mp4'],
                ['phrase' => 'Crush', 'video_path' => 'signs/phrases/Crush in Filipino Sign Language.mp4'],
                ['phrase' => 'Date', 'video_path' => 'signs/phrases/Date Variation 1 in Filipino Sign Language.mp4'],
                ['phrase' => 'Yellow', 'video_path' => 'signs/phrases/Dilaw (Yellow).mp4'],
                ['phrase' => 'Dilaw', 'video_path' => 'signs/phrases/Dilaw (Yellow).mp4'],
                ['phrase' => 'Dito ako nakatira', 'video_path' => 'signs/phrases/DITO AKO NAKATIRA.mp4'],
                ['phrase' => 'This is where I live', 'video_path' => 'signs/phrases/DITO AKO NAKATIRA.mp4'],
                ['phrase' => 'Edukasyon', 'video_path' => 'signs/phrases/Edukasyon (Education).mp4'],
                ['phrase' => 'Education', 'video_path' => 'signs/phrases/Edukasyon (Education).mp4'],
                ['phrase' => 'Pamilya', 'video_path' => 'signs/phrases/Family members in Filipino Sign Language.mp4'],
                ['phrase' => 'Family', 'video_path' => 'signs/phrases/Family members in Filipino Sign Language.mp4'],
                ['phrase' => 'Filipino Sign Language', 'video_path' => 'signs/phrases/Filipino Sign Language Variation 1 in Filipino Sign Language.mp4'],
                ['phrase' => 'From', 'video_path' => 'signs/phrases/FROM.mp4'],
                ['phrase' => 'Galing ako sa', 'video_path' => 'signs/phrases/GALING AKO SA.mp4'],
                ['phrase' => 'Ginto', 'video_path' => 'signs/phrases/Ginto (gold).mp4'],
                ['phrase' => 'Gold', 'video_path' => 'signs/phrases/Ginto (gold).mp4'],
                ['phrase' => 'Girlfriend', 'video_path' => 'signs/phrases/Girlfriend Variation 2 in Filipino Sign Language.mp4'],
                ['phrase' => 'Kasintahan', 'video_path' => 'signs/phrases/Girlfriend Variation 2 in Filipino Sign Language.mp4'],
                ['phrase' => 'Lolo', 'video_path' => 'signs/phrases/Grandfather in Filipino Sign Language.mp4'],
                ['phrase' => 'Grandfather', 'video_path' => 'signs/phrases/Grandfather in Filipino Sign Language.mp4'],
                ['phrase' => 'Lola', 'video_path' => 'signs/phrases/Grandmother in Filipino Sign Language.mp4'],
                ['phrase' => 'Grandmother', 'video_path' => 'signs/phrases/Grandmother in Filipino Sign Language.mp4'],
                ['phrase' => 'Guard', 'video_path' => 'signs/phrases/Guard Variation 2 in Filipino Sign Language.mp4'],
                ['phrase' => 'Gwardiya', 'video_path' => 'signs/phrases/Guard Variation 2 in Filipino Sign Language.mp4'],
                ['phrase' => 'Gwardya', 'video_path' => 'signs/phrases/Guard Variation 2 in Filipino Sign Language.mp4'],
                ['phrase' => 'Guro', 'video_path' => 'signs/phrases/Guro (Teacher) FSL .mp4'],
                ['phrase' => 'Teacher', 'video_path' => 'signs/phrases/Guro (Teacher) FSL .mp4'],
                ['phrase' => 'Gymnasium', 'video_path' => 'signs/phrases/Gymnasium in Filipino Sign Language.mp4'],
                ['phrase' => 'Maligayang Kaarawan', 'video_path' => 'signs/phrases/Happy Birthday ALL in Filipino Sign Language.mp4'],
                ['phrase' => 'Happy Birthday', 'video_path' => 'signs/phrases/Happy Birthday ALL in Filipino Sign Language.mp4'],
                ['phrase' => 'Happy new year', 'video_path' => 'signs/phrases/Happy New Year in Filipino Sign Language.mp4'],
                ['phrase' => 'Maligayang Bagong Taon', 'video_path' => 'signs/phrases/Happy New Year in Filipino Sign Language.mp4'],
                ['phrase' => 'Happy Valentines Day', 'video_path' => 'signs/phrases/Happy Valentine_s Day in Filipino Sign Language.mp4'],
                ['phrase' => 'he', 'video_path' => 'signs/phrases/HE SHE.mp4'],
                ['phrase' => 'she', 'video_path' => 'signs/phrases/HE SHE.mp4'],
                ['phrase' => 'heto', 'video_path' => 'signs/phrases/here.mp4'],
                ['phrase' => 'here', 'video_path' => 'signs/phrases/here.mp4'],
                ['phrase' => 'eto', 'video_path' => 'signs/phrases/here.mp4'],
                ['phrase' => 'Hikayatin', 'video_path' => 'signs/phrases/Hikayatin (Encourage).mp4'],
                ['phrase' => 'Encourage', 'video_path' => 'signs/phrases/Hikayatin (Encourage).mp4'],
                ['phrase' => 'His', 'video_path' => 'signs/phrases/HIS HER.mp4'],
                ['phrase' => 'Her', 'video_path' => 'signs/phrases/HIS HER.mp4'],
                ['phrase' => 'History', 'video_path' => 'signs/phrases/History in Filipino Sign Language.mp4'],
                ['phrase' => 'Kasaysayan', 'video_path' => 'signs/phrases/History in Filipino Sign Language.mp4'],
                ['phrase' => 'How Much', 'video_path' => 'signs/phrases/HOW MUCH.mp4'],
                ['phrase' => 'Magkano', 'video_path' => 'signs/phrases/HOW MUCH.mp4'],
                ['phrase' => 'Huminto sa Pag-aaral', 'video_path' => 'signs/phrases/Huminto sa pag-aaral FSL.mp4'],
                ['phrase' => 'Huminto sa pag aaral', 'video_path' => 'signs/phrases/Huminto sa pag-aaral FSL.mp4'],
                ['phrase' => 'Stopped School', 'video_path' => 'signs/phrases/Huminto sa pag-aaral FSL.mp4'],
                ['phrase' => 'Hindi ko alam', 'video_path' => 'signs/phrases/I DON_T KNOW.mp4'],
                ['phrase' => 'Di ko alam', 'video_path' => 'signs/phrases/I DON_T KNOW.mp4'],
                ['phrase' => 'I dont know', 'video_path' => 'signs/phrases/I DON_T KNOW.mp4'],
                ['phrase' => 'I hate you', 'video_path' => 'signs/phrases/I hate you Variation 1 in Filipino Sign Language.mp4'],
                ['phrase' => 'I like you', 'video_path' => 'signs/phrases/I like you in Filipino Sign Language.mp4'],
                ['phrase' => 'Gusto Kita', 'video_path' => 'signs/phrases/I want you in Filipino Sign Language.mp4'],
                ['phrase' => 'I miss you', 'video_path' => 'signs/phrases/I miss you in Filipino Sign Language.mp4'],
                ['phrase' => 'Miss na kita', 'video_path' => 'signs/phrases/I miss you in Filipino Sign Language.mp4'],
                ['phrase' => 'I really love you', 'video_path' => 'signs/phrases/I really love you Variation 2 in Filipino Sign Language.mp4'],
                ['phrase' => 'Mahal na mahal kita', 'video_path' => 'signs/phrases/I really love you Variation 2 in Filipino Sign Language.mp4'],
                ['phrase' => 'I want you', 'video_path' => 'signs/phrases/I want you in Filipino Sign Language.mp4'],
                ['phrase' => 'Ilan?', 'video_path' => 'signs/phrases/Ilan (How Many) FSL.mp4'],
                ['phrase' => 'How many?', 'video_path' => 'signs/phrases/Ilan (How Many) FSL.mp4'],
                ['phrase' => 'Ilan', 'video_path' => 'signs/phrases/Ilan (How Many) FSL.mp4'],
                ['phrase' => 'How many', 'video_path' => 'signs/phrases/Ilan (How Many) FSL.mp4'],
                ['phrase' => 'Independent', 'video_path' => 'signs/phrases/Independent in Filipino Sign Language.mp4'],
                ['phrase' => 'Inspired', 'video_path' => 'signs/phrases/Inspired in Filipino Sign Language.mp4'],
                ['phrase' => 'Iskolar', 'video_path' => 'signs/phrases/iskolar (Scholar) FSL.mp4'],
                ['phrase' => 'Scholar', 'video_path' => 'signs/phrases/iskolar (Scholar) FSL.mp4'],
                ['phrase' => 'Itim', 'video_path' => 'signs/phrases/Itim (Black).mp4'],
                ['phrase' => 'Black', 'video_path' => 'signs/phrases/Itim (Black).mp4'],
                ['phrase' => 'Kahel', 'video_path' => 'signs/phrases/kahel (orange).mp4'],
                ['phrase' => 'Orange', 'video_path' => 'signs/phrases/kahel (orange).mp4'],
                ['phrase' => 'Kaibigan', 'video_path' => 'signs/phrases/Kaibigan (bestfriend).mp4'],
                ['phrase' => 'Friend', 'video_path' => 'signs/phrases/Kaibigan (bestfriend).mp4'],
                ['phrase' => 'Kaibigan', 'video_path' => 'signs/phrases/Kaibigan (Friend) FSL.mp4'],
                ['phrase' => 'Bestfriend', 'video_path' => 'signs/phrases/Kaibigan (bestfriend).mp4'],
                ['phrase' => 'Best friend', 'video_path' => 'signs/phrases/Kaibigan (bestfriend).mp4'],
                ['phrase' => 'Kailan', 'video_path' => 'signs/phrases/Kailan (When) FSL.mp4'],
                ['phrase' => 'Kelan', 'video_path' => 'signs/phrases/Kailan (When) FSL.mp4'],
                ['phrase' => 'Kaylan', 'video_path' => 'signs/phrases/Kailan (When) FSL.mp4'],
                ['phrase' => 'When', 'video_path' => 'signs/phrases/Kailan (When) FSL.mp4'],
                ['phrase' => 'Kamag-aral', 'video_path' => 'signs/phrases/kamag-aral o kaklase (classmate) FSL.mp4'],
                ['phrase' => 'Kamagaral', 'video_path' => 'signs/phrases/kamag-aral o kaklase (classmate) FSL.mp4'],
                ['phrase' => 'Kamag aral', 'video_path' => 'signs/phrases/kamag-aral o kaklase (classmate) FSL.mp4'],
                ['phrase' => 'Classmate', 'video_path' => 'signs/phrases/kamag-aral o kaklase (classmate) FSL.mp4'],
                ['phrase' => 'Kaklase', 'video_path' => 'signs/phrases/kamag-aral o kaklase (classmate) FSL.mp4'],
                ['phrase' => 'Kanino', 'video_path' => 'signs/phrases/Kanino (Whom) FSL.mp4'],
                ['phrase' => 'Whom', 'video_path' => 'signs/phrases/Kanino (Whom) FSL.mp4'],
                ['phrase' => 'Kapansanan', 'video_path' => 'signs/phrases/Kapansanan FSL.mp4'],
                ['phrase' => 'Disability', 'video_path' => 'signs/phrases/Kapansanan FSL.mp4'],
                ['phrase' => 'Karapatan', 'video_path' => 'signs/phrases/karapatan (rights).mp4'],
                ['phrase' => 'Rights', 'video_path' => 'signs/phrases/karapatan (rights).mp4'],
                ['phrase' => 'Kayumanggi', 'video_path' => 'signs/phrases/Kayumanggi (Brown).mp4'],
                ['phrase' => 'Brown', 'video_path' => 'signs/phrases/Kayumanggi (Brown).mp4'],
                ['phrase' => 'Kilig', 'video_path' => 'signs/phrases/Kilig FSL.mp4'],
                ['phrase' => 'Klase', 'video_path' => 'signs/phrases/Klase (Class).mp4'],
                ['phrase' => 'Class', 'video_path' => 'signs/phrases/Klase (Class).mp4'],
                ['phrase' => 'Kulay abo', 'video_path' => 'signs/phrases/kulay abo (gray).mp4'],
                ['phrase' => 'Abo', 'video_path' => 'signs/phrases/kulay abo (gray).mp4'],
                ['phrase' => 'Ash', 'video_path' => 'signs/phrases/kulay abo (gray).mp4'],
                ['phrase' => 'Gray', 'video_path' => 'signs/phrases/kulay abo (gray).mp4'],
                ['phrase' => 'Kulay', 'video_path' => 'signs/phrases/Kulay.mp4'],
                ['phrase' => 'Color', 'video_path' => 'signs/phrases/Kulay.mp4'],
                ['phrase' => 'Lila', 'video_path' => 'signs/phrases/Lila (Violet).mp4'],
                ['phrase' => 'Violet', 'video_path' => 'signs/phrases/Lila (Violet).mp4'],
                ['phrase' => 'Lipat', 'video_path' => 'signs/phrases/Lipat, Paglipat (Transfer) FSL.mp4'],
                ['phrase' => 'Paglipat', 'video_path' => 'signs/phrases/Lipat, Paglipat (Transfer) FSL.mp4'],
                ['phrase' => 'Transfer', 'video_path' => 'signs/phrases/Lipat, Paglipat (Transfer) FSL.mp4'],
                ['phrase' => 'Live', 'video_path' => 'signs/phrases/live.mp4'],
                ['phrase' => 'Mabuhay', 'video_path' => 'signs/phrases/Mabuhay fsl.mp4'],
                ['phrase' => 'Mag-aaral', 'video_path' => 'signs/phrases/Mag-aaral o Estudyante (Student) FSL.mp4'],
                ['phrase' => 'Student', 'video_path' => 'signs/phrases/Mag-aaral o Estudyante (Student) FSL.mp4'],
                ['phrase' => 'Estudyante', 'video_path' => 'signs/phrases/Mag-aaral o Estudyante (Student) FSL.mp4'],
                ['phrase' => 'Studyante', 'video_path' => 'signs/phrases/Mag-aaral o Estudyante (Student) FSL.mp4'],
                ['phrase' => 'Magandang Gabi', 'video_path' => 'signs/phrases/Magandang Gabi (Good Evening) FSL .mp4'],
                ['phrase' => 'Good evening', 'video_path' => 'signs/phrases/Magandang Gabi (Good Evening) FSL .mp4'],
                ['phrase' => 'Magandang Gabi', 'video_path' => 'signs/phrases/Magandang Gabi (Goodnight) FSL.mp4'],
                ['phrase' => 'Good Night', 'video_path' => 'signs/phrases/Magandang Gabi (Goodnight) FSL.mp4'],
                ['phrase' => 'Magandang Hapon', 'video_path' => 'signs/phrases/Magandang Hapon FSL.mp4'],
                ['phrase' => 'Good afternoon', 'video_path' => 'signs/phrases/Magandang Hapon FSL.mp4'],
                ['phrase' => 'Magandang Tanghali', 'video_path' => 'signs/phrases/Magandang Tanghali FSL.mp4'],
                ['phrase' => 'Good Noon', 'video_path' => 'signs/phrases/Magandang Tanghali FSL.mp4'],
                ['phrase' => 'Magandang Umaga', 'video_path' => 'signs/phrases/Magandang Umaga FSL.mp4'],
                ['phrase' => 'Good Morning', 'video_path' => 'signs/phrases/Magandang Umaga FSL.mp4'],
                ['phrase' => 'Magkasama', 'video_path' => 'signs/phrases/Magkasama (Together) FSL.mp4'],
                ['phrase' => 'Together', 'video_path' => 'signs/phrases/Magkasama (Together) FSL.mp4'],
                ['phrase' => 'Mahal Kita', 'video_path' => 'signs/phrases/mahal kita (i love you).mp4'],
                ['phrase' => 'I love you', 'video_path' => 'signs/phrases/mahal kita (i love you).mp4'],
                ['phrase' => 'Malakas', 'video_path' => 'signs/phrases/malakas (strong) .mp4'],
                ['phrase' => 'Strong', 'video_path' => 'signs/phrases/malakas (strong) .mp4'],
                ['phrase' => 'Matapang', 'video_path' => 'signs/phrases/Matapang (Brave).mp4'],
                ['phrase' => 'Brave', 'video_path' => 'signs/phrases/Matapang (Brave).mp4'],
                ['phrase' => 'May crush ako sayo', 'video_path' => 'signs/phrases/May crush ako sa_yo (I have a crush on you) FSL.mp4'],
                ['phrase' => 'I have a crush on you', 'video_path' => 'signs/phrases/May crush ako sa_yo (I have a crush on you) FSL.mp4'],
                ['phrase' => 'Maybe', 'video_path' => 'signs/phrases/MAYBE.mp4'],
                ['phrase' => 'Baka', 'video_path' => 'signs/phrases/MAYBE.mp4'],
                ['phrase' => 'Me', 'video_path' => 'signs/phrases/ME I.mp4'],
                ['phrase' => 'I', 'video_path' => 'signs/phrases/ME I.mp4'],
                ['phrase' => 'Ako', 'video_path' => 'signs/phrases/ME I.mp4'],
                ['phrase' => 'Merry Christmas', 'video_path' => 'signs/phrases/Merry Christmas in Filipino Sign Language.mp4'],
                ['phrase' => 'Maligayang Pasko', 'video_path' => 'signs/phrases/Merry Christmas in Filipino Sign Language.mp4'],
                ['phrase' => 'Mine', 'video_path' => 'signs/phrases/MINE.mp4'],
                ['phrase' => 'Sakin', 'video_path' => 'signs/phrases/MINE.mp4'],
                ['phrase' => 'Nanay', 'video_path' => 'signs/phrases/Nanay, Mama, Ina (Mother) FSL.mp4'],
                ['phrase' => 'Mama', 'video_path' => 'signs/phrases/Nanay, Mama, Ina (Mother) FSL.mp4'],
                ['phrase' => 'Ina', 'video_path' => 'signs/phrases/Nanay, Mama, Ina (Mother) FSL.mp4'],
                ['phrase' => 'Mother', 'video_path' => 'signs/phrases/Nanay, Mama, Ina (Mother) FSL.mp4'],
                ['phrase' => 'No problem', 'video_path' => 'signs/phrases/NO PROBLEM.mp4'],
                ['phrase' => 'Walang problema', 'video_path' => 'signs/phrases/NO PROBLEM.mp4'],
                ['phrase' => 'Walang anuman', 'video_path' => 'signs/phrases/NO PROBLEM.mp4'],
                ['phrase' => 'No', 'video_path' => 'signs/phrases/NO.mp4'],
                ['phrase' => 'Hindi', 'video_path' => 'signs/phrases/NO.mp4'],
                ['phrase' => 'Not sure', 'video_path' => 'signs/phrases/NOT SURE.mp4'],
                ['phrase' => 'Hindi sigurado', 'video_path' => 'signs/phrases/NOT SURE.mp4'],
                ['phrase' => 'Ngayon', 'video_path' => 'signs/phrases/NOW.mp4'],
                ['phrase' => 'Now', 'video_path' => 'signs/phrases/NOW.mp4'],
                ['phrase' => 'Nowhere', 'video_path' => 'signs/phrases/NOWHERE.mp4'],
                ['phrase' => 'Office', 'video_path' => 'signs/phrases/Office in Filipino Sign Language.mp4'],
                ['phrase' => 'Opisina', 'video_path' => 'signs/phrases/Office in Filipino Sign Language.mp4'],
                ['phrase' => 'Oh I see', 'video_path' => 'signs/phrases/OH I SEE.mp4'],
                ['phrase' => 'Okay', 'video_path' => 'signs/phrases/OKAY.mp4'],
                ['phrase' => 'Our', 'video_path' => 'signs/phrases/OUR.mp4'],
                ['phrase' => 'Over there', 'video_path' => 'signs/phrases/OVER THERE.mp4'],
                ['phrase' => 'Paalam', 'video_path' => 'signs/phrases/Paalam FSL.mp4'],
                ['phrase' => 'Goodbye', 'video_path' => 'signs/phrases/Paalam FSL.mp4'],
                ['phrase' => 'Good bye', 'video_path' => 'signs/phrases/Paalam FSL.mp4'],
                ['phrase' => 'How', 'video_path' => 'signs/phrases/Paano (How) FSL.mp4'],
                ['phrase' => 'Paano', 'video_path' => 'signs/phrases/Paano (How) FSL.mp4'],
                ['phrase' => 'Paaralan', 'video_path' => 'signs/phrases/Paaralan (School) FSL.mp4'],
                ['phrase' => 'School', 'video_path' => 'signs/phrases/Paaralan (School) FSL.mp4'],
                ['phrase' => 'Pagbati', 'video_path' => 'signs/phrases/Pagbati, Binabati kita (Congratulations) FSL.mp4'],
                ['phrase' => 'Binabati Kita', 'video_path' => 'signs/phrases/Pagbati, Binabati kita (Congratulations) FSL.mp4'],
                ['phrase' => 'Congratulation', 'video_path' => 'signs/phrases/Pagbati, Binabati kita (Congratulations) FSL.mp4'],
                ['phrase' => 'Congrats', 'video_path' => 'signs/phrases/Pagbati, Binabati kita (Congratulations) FSL.mp4'],
                ['phrase' => 'Pagdiwang', 'video_path' => 'signs/phrases/pagdiwang, pagdiriwang (celebration).mp4'],
                ['phrase' => 'Pagdiriwang', 'video_path' => 'signs/phrases/pagdiwang, pagdiriwang (celebration).mp4'],
                ['phrase' => 'Celebration', 'video_path' => 'signs/phrases/pagdiwang, pagdiriwang (celebration).mp4'],
                ['phrase' => 'Pag ibig', 'video_path' => 'signs/phrases/Pag-ibig, pagmamahal, (Love) .mp4'],
                ['phrase' => 'Pag-ibig', 'video_path' => 'signs/phrases/Pag-ibig, pagmamahal, (Love) .mp4'],
                ['phrase' => 'Pagmamahal', 'video_path' => 'signs/phrases/Pag-ibig, pagmamahal, (Love) .mp4'],
                ['phrase' => 'Love', 'video_path' => 'signs/phrases/Pag-ibig, pagmamahal, (Love) .mp4'],
                ['phrase' => 'Pagkakapantay-pantay', 'video_path' => 'signs/phrases/pagkakapantay-pantay (Equality) .mp4'],
                ['phrase' => 'Pagkakapantay pantay', 'video_path' => 'signs/phrases/pagkakapantay-pantay (Equality) .mp4'],
                ['phrase' => 'Equality', 'video_path' => 'signs/phrases/pagkakapantay-pantay (Equality) .mp4'],
                ['phrase' => 'Pagtapos', 'video_path' => 'signs/phrases/Pagtatapos (Graduation).mp4'],
                ['phrase' => 'Graduation', 'video_path' => 'signs/phrases/Pagtatapos (Graduation).mp4'],
                ['phrase' => 'Palakpak', 'video_path' => 'signs/phrases/Palakpak (Applause).mp4'],
                ['phrase' => 'Applause', 'video_path' => 'signs/phrases/Palakpak (Applause).mp4'],
                ['phrase' => 'Partner', 'video_path' => 'signs/phrases/Partner in Filipino Sign Language.mp4'],
                ['phrase' => 'Punong-guro', 'video_path' => 'signs/phrases/Principal in Filipino Sign Language.mp4'],
                ['phrase' => 'Punong guro', 'video_path' => 'signs/phrases/Principal in Filipino Sign Language.mp4'],
                ['phrase' => 'Principal', 'video_path' => 'signs/phrases/Principal in Filipino Sign Language.mp4'],
                ['phrase' => 'Principals Office', 'video_path' => 'signs/phrases/Principal_s Office in Filipino Sign Language.mp4'],
                ['phrase' => 'Principal Office', 'video_path' => 'signs/phrases/Principal_s Office in Filipino Sign Language.mp4'],
                ['phrase' => 'Tanggapan ng Punong-guro', 'video_path' => 'signs/phrases/Principal_s Office in Filipino Sign Language.mp4'],
                ['phrase' => 'Tanggapan ng punong guro', 'video_path' => 'signs/phrases/Principal_s Office in Filipino Sign Language.mp4'],
                ['phrase' => 'Problem', 'video_path' => 'signs/phrases/PROBLEM.mp4'],
                ['phrase' => 'Problema', 'video_path' => 'signs/phrases/PROBLEM.mp4'],
                ['phrase' => 'Progressive Pronoun', 'video_path' => 'signs/phrases/PROGRESSIVE PRONOUN.mp4'],
                ['phrase' => 'Pronoun', 'video_path' => 'signs/phrases/PRONOUNS.mp4'],
                ['phrase' => 'Pula', 'video_path' => 'signs/phrases/Pula (Red).mp4'],
                ['phrase' => 'Red', 'video_path' => 'signs/phrases/Pula (Red).mp4'],
                ['phrase' => 'Puti', 'video_path' => 'signs/phrases/Puti (White).mp4'],
                ['phrase' => 'White', 'video_path' => 'signs/phrases/Puti (White).mp4'],
                ['phrase' => 'Respeto', 'video_path' => 'signs/phrases/Respeto (Respect) .mp4'],
                ['phrase' => 'Respect', 'video_path' => 'signs/phrases/Respeto (Respect) .mp4'],
                ['phrase' => 'Kulay Rosas', 'video_path' => 'signs/phrases/Rosas (Pink).mp4'],
                ['phrase' => 'Pink', 'video_path' => 'signs/phrases/Rosas (Pink).mp4'],
                ['phrase' => 'Rosas', 'video_path' => 'signs/phrases/Rosas (Pink).mp4'],
                ['phrase' => 'Saan', 'video_path' => 'signs/phrases/Saan (Where) FSL.mp4'],
                ['phrase' => 'Where', 'video_path' => 'signs/phrases/Saan (Where) FSL.mp4'],
                ['phrase' => 'Salamat', 'video_path' => 'signs/phrases/Salamat (Thank You) FSL.mp4'],
                ['phrase' => 'Thank You', 'video_path' => 'signs/phrases/Salamat (Thank You) FSL.mp4'],
                ['phrase' => 'Self Love', 'video_path' => 'signs/phrases/Self love Variation 2 in Filipino Sign Language.mp4'],
                ['phrase' => 'Self-Love', 'video_path' => 'signs/phrases/Self love Variation 2 in Filipino Sign Language.mp4'],
                ['phrase' => 'Signing Words', 'video_path' => 'signs/phrases/SIGNING WORDS.mp4'],
                ['phrase' => 'Single', 'video_path' => 'signs/phrases/Single in Filipino Sign Language.mp4'],
                ['phrase' => 'Sino', 'video_path' => 'signs/phrases/Sino (Who) FSL.mp4'],
                ['phrase' => 'Who', 'video_path' => 'signs/phrases/Sino (Who) FSL.mp4'],
                ['phrase' => 'Sister', 'video_path' => 'signs/phrases/Sister in Filipino Sign Language.mp4'],
                ['phrase' => 'Ate', 'video_path' => 'signs/phrases/Sister in Filipino Sign Language.mp4'],
                ['phrase' => 'Somewhere', 'video_path' => 'signs/phrases/SOMEWHERE.mp4'],
                ['phrase' => 'Kung saan', 'video_path' => 'signs/phrases/SOMEWHERE.mp4'],
                ['phrase' => 'Struggle', 'video_path' => 'signs/phrases/Struggle Variation 1 in Filipino Sign Language.mp4'],
                ['phrase' => 'Suporta', 'video_path' => 'signs/phrases/suporta (support) FSL.mp4'],
                ['phrase' => 'Supporta', 'video_path' => 'signs/phrases/suporta (support) FSL.mp4'],
                ['phrase' => 'Support', 'video_path' => 'signs/phrases/suporta (support) FSL.mp4'],
                ['phrase' => 'Sure', 'video_path' => 'signs/phrases/SURE.mp4'],
                ['phrase' => 'Sige', 'video_path' => 'signs/phrases/SURE.mp4'],
                ['phrase' => 'Sweetheart', 'video_path' => 'signs/phrases/Sweetheart in Filipino Sign Language.mp4'],
                ['phrase' => 'Sweet heart', 'video_path' => 'signs/phrases/Sweetheart in Filipino Sign Language.mp4'],
                ['phrase' => 'Taga saan ka?', 'video_path' => 'signs/phrases/TAGA SAAN KA.mp4'],
                ['phrase' => 'Where are you from?', 'video_path' => 'signs/phrases/TAGA SAAN KA.mp4'],
                ['phrase' => 'Taga saan ka', 'video_path' => 'signs/phrases/TAGA SAAN KA.mp4'],
                ['phrase' => 'Where are you from', 'video_path' => 'signs/phrases/TAGA SAAN KA.mp4'],
                ['phrase' => 'Theatre', 'video_path' => 'signs/phrases/Theater in Filipino Sign Language.mp4'],
                ['phrase' => 'Teatro', 'video_path' => 'signs/phrases/Theater in Filipino Sign Language.mp4'],
                ['phrase' => 'Their', 'video_path' => 'signs/phrases/THEIR.mp4'],
                ['phrase' => 'Them', 'video_path' => 'signs/phrases/THEM.mp4'],
                ['phrase' => 'Undas', 'video_path' => 'signs/phrases/Undas Variation 1 in Filipino Sign Language.mp4'],
                ['phrase' => 'Unibersidad', 'video_path' => 'signs/phrases/Unibersidad (University) FSL.mp4'],
                ['phrase' => 'University', 'video_path' => 'signs/phrases/Unibersidad (University) FSL.mp4'],
                ['phrase' => 'Wait', 'video_path' => 'signs/phrases/WAIT.mp4'],
                ['phrase' => 'Teka', 'video_path' => 'signs/phrases/WAIT.mp4'],
                ['phrase' => 'Welcome', 'video_path' => 'signs/phrases/Walang anuman (welcome) fsl.mp4'],
                ['phrase' => 'Walang anuman', 'video_path' => 'signs/phrases/Walang anuman (welcome) fsl.mp4'],
                ['phrase' => 'We', 'video_path' => 'signs/phrases/WE.mp4'],
                ['phrase' => 'Whatever', 'video_path' => 'signs/phrases/WHATEVER.mp4'],
                ['phrase' => 'Which', 'video_path' => 'signs/phrases/WHICH.mp4'],
                ['phrase' => 'Wow', 'video_path' => 'signs/phrases/WOW.mp4'],
                ['phrase' => 'Yes', 'video_path' => 'signs/phrases/YES.mp4'],
                ['phrase' => 'Oo', 'video_path' => 'signs/phrases/YES.mp4'],
                ['phrase' => 'You', 'video_path' => 'signs/phrases/YOU.mp4'],
                ['phrase' => 'Ikaw', 'video_path' => 'signs/phrases/YOU.mp4'],
                ['phrase' => 'Your', 'video_path' => 'signs/phrases/YOUR.mp4'],

                ['phrase' => 'Adobo', 'video_path' => 'signs/phrases/adobo.mp4'],
                ['phrase' => 'Pork Braised', 'video_path' => 'signs/phrases/adobo.mp4'],
                ['phrase' => 'Ah Ganun', 'video_path' => 'signs/phrases/Ah Ganun (Oh i see).mp4'],
                ['phrase' => 'Oh I See', 'video_path' => 'signs/phrases/Ah Ganun (Oh i see).mp4'],
                ['phrase' => 'Ako ay mabuti', 'video_path' => 'signs/phrases/Ako ay Mabuti (I am fine) - Made with Clipchamp.mp4'],
                ['phrase' => 'I am fine', 'video_path' => 'signs/phrases/YOURAko ay Mabuti (I am fine) - Made with Clipchamp.mp4'],
                ['phrase' => 'I\'m Fine', 'video_path' => 'signs/phrases/Ako ay Mabuti (I am fine) - Made with Clipchamp.mp4'],
                ['phrase' => 'Anong pangalan mo?', 'video_path' => 'signs/phrases/Ano pangalan mo_ (What_s your name).mp4'],
                ['phrase' => 'Anong pangalan mo', 'video_path' => 'signs/phrases/Ano pangalan mo_ (What_s your name).mp4'],
                ['phrase' => 'Ano pangalan mo?', 'video_path' => 'signs/phrases/Ano pangalan mo_ (What_s your name).mp4'],
                ['phrase' => 'Ano pangalan mo', 'video_path' => 'signs/phrases/Ano pangalan mo_ (What_s your name).mp4'],
                ['phrase' => 'What is your name?', 'video_path' => 'signs/phrases/Ano pangalan mo_ (What_s your name).mp4'],
                ['phrase' => 'What is your name', 'video_path' => 'signs/phrases/Ano pangalan mo_ (What_s your name).mp4'],
                ['phrase' => 'What\'s your name', 'video_path' => 'signs/phrases/Ano pangalan mo_ (What_s your name).mp4'],
                ['phrase' => 'What\'s your name?', 'video_path' => 'signs/phrases/Ano pangalan mo_ (What_s your name).mp4'],
                ['phrase' => 'Anong ginagawa mo?', 'video_path' => 'signs/phrases/Anong ginagawa mo_ (What are you doing_).mp4'],
                ['phrase' => 'Anong ginagawa mo', 'video_path' => 'signs/phrases/Anong ginagawa mo_ (What are you doing_).mp4'],
                ['phrase' => 'What are you doing?', 'video_path' => 'signs/phrases/Anong ginagawa mo_ (What are you doing_).mp4'],
                ['phrase' => 'What are you doing', 'video_path' => 'signs/phrases/Anong ginagawa mo_ (What are you doing_).mp4'],
                ['phrase' => 'Brown rice', 'video_path' => 'signs/phrases/brown rice.mp4'],
                ['phrase' => 'Kanin', 'video_path' => 'signs/phrases/brown rice.mp4'],
                ['phrase' => 'Rice', 'video_path' => 'signs/phrases/brown rice.mp4'],
                ['phrase' => 'Cebu', 'video_path' => 'signs/phrases/Cebu.mp4'],
                ['phrase' => 'Cereal', 'video_path' => 'signs/phrases/cereal.mp4'],
                ['phrase' => 'Congratulations', 'video_path' => 'signs/phrases/congratulations congrats.mp4'],
                ['phrase' => 'Congrats', 'video_path' => 'signs/phrases/congratulations congrats.mp4'],
                ['phrase' => 'Davao', 'video_path' => 'signs/phrases/Davao.mp4'],
                ['phrase' => 'Dinner', 'video_path' => 'signs/phrases/dinner hapunan.mp4'],
                ['phrase' => 'Hapunan', 'video_path' => 'signs/phrases/dinner hapunan.mp4'],
                ['phrase' => 'I don\'t understand', 'video_path' => 'signs/phrases/don_t understand hindi ko maintindihan.mp4'],
                ['phrase' => 'I dont understand', 'video_path' => 'signs/phrases/don_t understand hindi ko maintindihan.mp4'],
                ['phrase' => 'Di ko maintindihan', 'video_path' => 'signs/phrases/don_t understand hindi ko maintindihan.mp4'],
                ['phrase' => 'Hindi ko maintindihan', 'video_path' => 'signs/phrases/don_t understand hindi ko maintindihan.mp4'],
                ['phrase' => 'Excuse me', 'video_path' => 'signs/phrases/EXCUSE ME.mp4'],
                ['phrase' => 'Fried Chicken', 'video_path' => 'signs/phrases/fried chicken manok.mp4'],
                ['phrase' => 'Pritong Manok', 'video_path' => 'signs/phrases/fried chicken manok.mp4'],
                ['phrase' => 'Prinitong Manok', 'video_path' => 'signs/phrases/fried chicken manok.mp4'],
                ['phrase' => 'Piniritong Manok', 'video_path' => 'signs/phrases/fried chicken manok.mp4'],
                ['phrase' => 'Good afternoon', 'video_path' => 'signs/phrases/good afternoon.mp4'],
                ['phrase' => 'Magandang Hapon', 'video_path' => 'signs/phrases/good afternoon.mp4'],
                ['phrase' => 'Good evening', 'video_path' => 'signs/phrases/good evening.mp4'],
                ['phrase' => 'Magandang Gabi', 'video_path' => 'signs/phrases/good evening.mp4'],
                ['phrase' => 'Good Midnight', 'video_path' => 'signs/phrases/good midnight.mp4'],
                ['phrase' => 'Magandang Hatinggabi', 'video_path' => 'signs/phrases/good midnight.mp4'],
                ['phrase' => 'Magandang Hating-gabi', 'video_path' => 'signs/phrases/good midnight.mp4'],
                ['phrase' => 'Good Morning', 'video_path' => 'signs/phrases/good morning.mp4'],
                ['phrase' => 'Magandang Umaga', 'video_path' => 'signs/phrases/good morning.mp4'],
                ['phrase' => 'Good Night', 'video_path' => 'signs/phrases/good night.mp4'],
                ['phrase' => 'How are you?', 'video_path' => 'signs/phrases/how are you or kumusta ka.mp4'],
                ['phrase' => 'How are you', 'video_path' => 'signs/phrases/how are you or kumusta ka.mp4'],
                ['phrase' => 'Kumusta ka?', 'video_path' => 'signs/phrases/how are you or kumusta ka.mp4'],
                ['phrase' => 'Kumusta ka', 'video_path' => 'signs/phrases/how are you or kumusta ka.mp4'],
                ['phrase' => 'Kamusta ka?', 'video_path' => 'signs/phrases/how are you or kumusta ka.mp4'],
                ['phrase' => 'Kamusta ka', 'video_path' => 'signs/phrases/how are you or kumusta ka.mp4'],
                ['phrase' => 'Hurry', 'video_path' => 'signs/phrases/hurry bilisan.mp4'],
                ['phrase' => 'Bilisan', 'video_path' => 'signs/phrases/hurry bilisan.mp4'],
                ['phrase' => 'Hurry up', 'video_path' => 'signs/phrases/hurry bilisan.mp4'],
                ['phrase' => 'Ilocos Norte', 'video_path' => 'signs/phrases/Ilocos Norte.mp4'],
                ['phrase' => 'Ilocos Sur', 'video_path' => 'signs/phrases/Ilocos Sur.mp4'],
                ['phrase' => 'I\'m fine', 'video_path' => 'signs/phrases/im fine.mp4'],
                ['phrase' => 'Okay lang ako', 'video_path' => 'signs/phrases/im fine.mp4'],
                ['phrase' => 'Im Fine', 'video_path' => 'signs/phrases/im fine.mp4'],
                ['phrase' => 'I\m not Fine', 'video_path' => 'signs/phrases/im not fine.mp4'],
                ['phrase' => 'Im not fine', 'video_path' => 'signs/phrases/im not fine.mp4'],
                ['phrase' => 'Hindi ako Okay', 'video_path' => 'signs/phrases/im not fine.mp4'],
                ['phrase' => 'Di ako okay', 'video_path' => 'signs/phrases/im not fine.mp4'],
                ['phrase' => 'Inihaw', 'video_path' => 'signs/phrases/inihaw ihaw.mp4'],
                ['phrase' => 'Ihaw', 'video_path' => 'signs/phrases/inihaw ihaw.mp4'],
                ['phrase' => 'Roasted', 'video_path' => 'signs/phrases/inihaw ihaw.mp4'],
                ['phrase' => 'Grilled', 'video_path' => 'signs/phrases/inihaw ihaw.mp4'],
                ['phrase' => 'Broiled', 'video_path' => 'signs/phrases/inihaw ihaw.mp4'],
                ['phrase' => 'Inihaw na baboy', 'video_path' => 'signs/phrases/inihaw na baboy.mp4'],
                ['phrase' => 'Grilled pork', 'video_path' => 'signs/phrases/inihaw na baboy.mp4'],
                ['phrase' => 'Inihaw na bangus', 'video_path' => 'signs/phrases/inihaw na bangus.mp4'],
                ['phrase' => 'Grilled Milkfish', 'video_path' => 'signs/phrases/inihaw na bangus.mp4'],
                ['phrase' => 'Grilled Bangus', 'video_path' => 'signs/phrases/inihaw na bangus.mp4'],
                ['phrase' => 'Inihaw na Manok', 'video_path' => 'signs/phrases/inihaw na manok.mp4'],
                ['phrase' => 'Grilled Chicken', 'video_path' => 'signs/phrases/inihaw na manok.mp4'],
                ['phrase' => 'Kalabaw', 'video_path' => 'signs/phrases/Kalabaw (Carabao).mp4'],
                ['phrase' => 'Carabao', 'video_path' => 'signs/phrases/Kalabaw (Carabao).mp4'],
                ['phrase' => 'Kamusta ka na?', 'video_path' => 'signs/phrases/Kamusta ka na_ (How are you_) - Made with Clipchamp.mp4'],
                ['phrase' => 'Kamusta ka na', 'video_path' => 'signs/phrases/Kamusta ka na_ (How are you_) - Made with Clipchamp.mp4'],
                ['phrase' => 'Kumusta ka na?', 'video_path' => 'signs/phrases/Kamusta ka na_ (How are you_) - Made with Clipchamp.mp4'],
                ['phrase' => 'Kumusta ka na', 'video_path' => 'signs/phrases/Kamusta ka na_ (How are you_) - Made with Clipchamp.mp4'],
                ['phrase' => 'How are you?', 'video_path' => 'signs/phrases/Kamusta ka na_ (How are you_) - Made with Clipchamp.mp4'],
                ['phrase' => 'How are you', 'video_path' => 'signs/phrases/Kamusta ka na_ (How are you_) - Made with Clipchamp.mp4'],
                ['phrase' => 'Kanin', 'video_path' => 'signs/phrases/kanin rice.mp4'],
                ['phrase' => 'Rice', 'video_path' => 'signs/phrases/kanin rice.mp4'],
                ['phrase' => 'Kumain ka ng maraming kanin', 'video_path' => 'signs/phrases/kumain ka ng maraming kanin.mp4'],
                ['phrase' => 'Eat a lot of rice', 'video_path' => 'signs/phrases/kumain ka ng maraming kanin.mp4'],
                ['phrase' => 'Later', 'video_path' => 'signs/phrases/later mamaya.mp4'],
                ['phrase' => 'Mamaya', 'video_path' => 'signs/phrases/later mamaya.mp4'],
                ['phrase' => 'Longganisa', 'video_path' => 'signs/phrases/longganisa.mp4'],
                ['phrase' => 'Longganisa', 'video_path' => 'signs/phrases/longganisa.mp4'],
                ['phrase' => 'Lumpia', 'video_path' => 'signs/phrases/lumpia.mp4'],
                ['phrase' => 'Lunch', 'video_path' => 'signs/phrases/lunch tanghalian.mp4'],
                ['phrase' => 'Tanghalian', 'video_path' => 'signs/phrases/lunch tanghalian.mp4'],
                ['phrase' => 'Mabuti ako', 'video_path' => 'signs/phrases/Mabuti ako (I_m Great) - Made with Clipchamp.mp4'],
                ['phrase' => 'I\'m great', 'video_path' => 'signs/phrases/Mabuti ako (I_m Great) - Made with Clipchamp.mp4'],
                ['phrase' => 'I\'m fine', 'video_path' => 'signs/phrases/Mabuti ako (I_m Great) - Made with Clipchamp.mp4'],
                ['phrase' => 'Magandang Gabi', 'video_path' => 'signs/phrases/Magandang Gabi (Good Evening) - Made with Clipchamp.mp4'],
                ['phrase' => 'Good evening', 'video_path' => 'signs/phrases/Magandang Gabi (Good Evening) - Made with Clipchamp.mp4'],
                ['phrase' => 'Magandang Hapon', 'video_path' => 'signs/phrases/Magandang Hapon (Good Afternoon) - Made with Clipchamp.mp4'],
                ['phrase' => 'Good afternoon', 'video_path' => 'signs/phrases/Magandang Hapon (Good Afternoon) - Made with Clipchamp.mp4'],
                ['phrase' => 'Magandang Umaga', 'video_path' => 'signs/phrases/Magandang Umaga (Good Morning) - Made with Clipchamp.mp4'],
                ['phrase' => 'Good Morning', 'video_path' => 'signs/phrases/Magandang Umaga (Good Morning) - Made with Clipchamp.mp4'],
                ['phrase' => 'Magkita tayo mamaya', 'video_path' => 'signs/phrases/Magkita tayo mamaya (See you later) - Made with Clipchamp.mp4'],
                ['phrase' => 'Let\'s meet later', 'video_path' => 'signs/phrases/Magkita tayo mamaya (See you later) - Made with Clipchamp.mp4'],
                ['phrase' => 'Lets meet later', 'video_path' => 'signs/phrases/Magkita tayo mamaya (See you later) - Made with Clipchamp.mp4'],
                ['phrase' => 'See you later', 'video_path' => 'signs/phrases/Magkita tayo mamaya (See you later) - Made with Clipchamp.mp4'],
                ['phrase' => 'Malapit', 'video_path' => 'signs/phrases/Malapit (Near).mp4'],
                ['phrase' => 'Near', 'video_path' => 'signs/phrases/Malapit (Near).mp4'],
                ['phrase' => 'Manila', 'video_path' => 'signs/phrases/Manila.mp4'],
                ['phrase' => 'Mantikilya', 'video_path' => 'signs/phrases/mantikilya butter.mp4'],
                ['phrase' => 'Butter', 'video_path' => 'signs/phrases/mantikilya butter.mp4'],
                ['phrase' => 'Maraming salamat', 'video_path' => 'signs/phrases/Maraming salamat (2) (Thank you very much).mp4'],
                ['phrase' => 'Thank you so much', 'video_path' => 'signs/phrases/Maraming salamat (2) (Thank you very much).mp4'],
                ['phrase' => 'Thank you very much', 'video_path' => 'signs/phrases/Maraming salamat (2) (Thank you very much).mp4'],
                ['phrase' => 'Masaya akong nakilala ka', 'video_path' => 'signs/phrases/Masaya akong makilala ka (Nice to meet you).mp4'],
                ['phrase' => 'It\'s nice to meet you', 'video_path' => 'signs/phrases/Masaya akong makilala ka (Nice to meet you).mp4'],
                ['phrase' => 'Its nice to meet you', 'video_path' => 'signs/phrases/Masaya akong makilala ka (Nice to meet you).mp4'],
                ['phrase' => 'Nice to meet you', 'video_path' => 'signs/phrases/Masaya akong makilala ka (Nice to meet you).mp4'],
                ['phrase' => 'Maybe', 'video_path' => 'signs/phrases/maybe siguro.mp4'],
                ['phrase' => 'Siguro', 'video_path' => 'signs/phrases/maybe siguro.mp4'],
                ['phrase' => 'Nakuha ko na', 'video_path' => 'signs/phrases/nakuha ko na.mp4'],
                ['phrase' => 'Ah I get it now', 'video_path' => 'signs/phrases/nakuha ko na.mp4'],
                ['phrase' => 'I get it', 'video_path' => 'signs/phrases/nakuha ko na.mp4'],
                ['phrase' => 'I get it now', 'video_path' => 'signs/phrases/nakuha ko na.mp4'],
                ['phrase' => 'Nice to meet you', 'video_path' => 'signs/phrases/nice to meet you.mp4'],
                ['phrase' => 'Ikinagagalak kitang makilala', 'video_path' => 'signs/phrases/nice to meet you.mp4'],
                ['phrase' => 'No', 'video_path' => 'signs/phrases/no hindi.mp4'],
                ['phrase' => 'Hindi', 'video_path' => 'signs/phrases/no hindi.mp4'],
                ['phrase' => 'Now', 'video_path' => 'signs/phrases/now ngayon.mp4'],
                ['phrase' => 'Ngayon', 'video_path' => 'signs/phrases/now ngayon.mp4'],
                ['phrase' => 'Paksiw na bangus', 'video_path' => 'signs/phrases/paksiw.mp4'],
                ['phrase' => 'Pancake', 'video_path' => 'signs/phrases/pancake.mp4'],
                ['phrase' => 'Pansit', 'video_path' => 'signs/phrases/pansit pancit.mp4'],
                ['phrase' => 'Pancit', 'video_path' => 'signs/phrases/pansit pancit.mp4'],
                ['phrase' => 'Paumanhin ano yon?', 'video_path' => 'signs/phrases/Paumanhin ano yon_ (I_m sorry).mp4'],
                ['phrase' => 'Pardon?', 'video_path' => 'signs/phrases/Paumanhin ano yon_ (I_m sorry).mp4'],
                ['phrase' => 'I\'m sorry?', 'video_path' => 'signs/phrases/Paumanhin ano yon_ (I_m sorry).mp4'],
                ['phrase' => 'Saan ka nagmula?', 'video_path' => 'signs/phrases/Saan ka nagmula_ (Where did you come from_).mp4'],
                ['phrase' => 'San ka nagmula?', 'video_path' => 'signs/phrases/Saan ka nagmula_ (Where did you come from_).mp4'],
                ['phrase' => 'Where did you come from?', 'video_path' => 'signs/phrases/Saan ka nagmula_ (Where did you come from_).mp4'],
                ['phrase' => 'See you later', 'video_path' => 'signs/phrases/see you later.mp4'],
                ['phrase' => 'See you next time', 'video_path' => 'signs/phrases/see you next time.mp4'],
                ['phrase' => 'Sa susunod muli', 'video_path' => 'signs/phrases/see you next time.mp4'],
                ['phrase' => 'See you tomorrow', 'video_path' => 'signs/phrases/see you tomorrow.mp4'],
                ['phrase' => 'Sorry', 'video_path' => 'signs/phrases/sorry pasensya paumanhin po.mp4'],
                ['phrase' => 'Sorry po', 'video_path' => 'signs/phrases/sorry pasensya paumanhin po.mp4'],
                ['phrase' => 'Pasensya', 'video_path' => 'signs/phrases/sorry pasensya paumanhin po.mp4'],
                ['phrase' => 'Paumanhin', 'video_path' => 'signs/phrases/sorry pasensya paumanhin po.mp4'],
                ['phrase' => 'Strawberry Jam', 'video_path' => 'signs/phrases/strawberry jam.mp4'],
                ['phrase' => 'Sure', 'video_path' => 'signs/phrases/sure sige.mp4'],
                ['phrase' => 'Sige', 'video_path' => 'signs/phrases/sure sige.mp4'],
                ['phrase' => 'Take care', 'video_path' => 'signs/phrases/take care ingat ka.mp4'],
                ['phrase' => 'Ingat ka', 'video_path' => 'signs/phrases/take care ingat ka.mp4'],
                ['phrase' => 'Ingat', 'video_path' => 'signs/phrases/take care ingat ka.mp4'],
                ['phrase' => 'Thank you', 'video_path' => 'signs/phrases/thank you salamat.mp4'],
                ['phrase' => 'Salamat', 'video_path' => 'signs/phrases/thank you salamat.mp4'],
                ['phrase' => 'Tinapay', 'video_path' => 'signs/phrases/tinapay toast .mp4'],
                ['phrase' => 'Toast', 'video_path' => 'signs/phrases/tinapay toast .mp4'],
                ['phrase' => 'Understand', 'video_path' => 'signs/phrases/understand.mp4'],
                ['phrase' => 'Wait', 'video_path' => 'signs/phrases/wait sandali lang.mp4'],
                ['phrase' => 'Sandali lang', 'video_path' => 'signs/phrases/wait sandali lang.mp4'],
                ['phrase' => 'Wala lang', 'video_path' => 'signs/phrases/Wala lang (Nothing much).mp4'],
                ['phrase' => 'Nothing', 'video_path' => 'signs/phrases/Wala lang (Nothing much).mp4'],
                ['phrase' => 'Nothing much', 'video_path' => 'signs/phrases/Wala lang (Nothing much).mp4'],
                ['phrase' => 'It\'s Nothing', 'video_path' => 'signs/phrases/Wala lang (Nothing much).mp4'],
                ['phrase' => 'What are you doing?', 'video_path' => 'signs/phrases/what are you doing anong ginagawa mo.mp4'],
                ['phrase' => 'Anong ginagawa mo?', 'video_path' => 'signs/phrases/what are you doing anong ginagawa mo.mp4'],
                ['phrase' => 'What is your name?', 'video_path' => 'signs/phrases/what is your name anong pangalan mo.mp4'],
                ['phrase' => 'What\'s your name?', 'video_path' => 'signs/phrases/what is your name anong pangalan mo.mp4'],
                ['phrase' => 'Anong pangalan mo?', 'video_path' => 'signs/phrases/what is your name anong pangalan mo.mp4'],
                ['phrase' => 'What\'s up?', 'video_path' => 'signs/phrases/what_s up.mp4'],
                ['phrase' => 'Kumusta', 'video_path' => 'signs/phrases/what_s up.mp4'],
                ['phrase' => 'White Rice', 'video_path' => 'signs/phrases/white rice.mp4'],
                ['phrase' => 'Yes', 'video_path' => 'signs/phrases/yes oo.mp4'],
                ['phrase' => 'Oo', 'video_path' => 'signs/phrases/yes oo.mp4'],
                ['phrase' => 'You are welcome', 'video_path' => 'signs/phrases/youre welcome walang anuman.mp4'],
                ['phrase' => 'You\'re welcome', 'video_path' => 'signs/phrases/youre welcome walang anuman.mp4'],
                ['phrase' => 'Mabuti ako', 'video_path' => 'signs/phrases/MABUTI AKO IM FINE.mp4'],
                ['phrase' => 'I\'m fine', 'video_path' => 'signs/phrases/MABUTI AKO IM FINE.mp4'],
                ['phrase' => 'How have you been?', 'video_path' => 'signs/phrases/how have you been. kumusta ang buhay.mp4'],
                ['phrase' => 'Kumusta ang buhay?', 'video_path' => 'signs/phrases/how have you been. kumusta ang buhay.mp4'],
                ['phrase' => 'I\'m feeling bad', 'video_path' => 'signs/phrases/IM FEELING BAD MASAMA ANG AKING PAKIRAMDAM.mp4'],
                ['phrase' => 'Masama ang pakiramdam ko', 'video_path' => 'signs/phrases/IM FEELING BAD MASAMA ANG AKING PAKIRAMDAM.mp4'],
                ['phrase' => 'Masama ang pakiramdam', 'video_path' => 'signs/phrases/IM FEELING BAD MASAMA ANG AKING PAKIRAMDAM.mp4'],
                ['phrase' => 'I\'m good', 'video_path' => 'signs/phrases/IM GOOD.mp4'],
                ['phrase' => 'I\'m pretty good', 'video_path' => 'signs/phrases/im pretty good.mp4'],
                ['phrase' => 'How are you?', 'video_path' => 'signs/phrases/KUMUSTA KA NA HOW ARE YOU.mp4'],
                ['phrase' => 'Kumusta ka na?', 'video_path' => 'signs/phrases/KUMUSTA KA NA HOW ARE YOU.mp4'],
                ['phrase' => 'Maayos ako', 'video_path' => 'signs/phrases/MAAYOS AKO, MABUTI AKO, IM GREAT, IM GOOD.mp4'],
                ['phrase' => 'I\'m great', 'video_path' => 'signs/phrases/MAAYOS AKO, MABUTI AKO, IM GREAT, IM GOOD.mp4'],
                ['phrase' => 'Not bad', 'video_path' => 'signs/phrases/NOT BAD.mp4'],
                ['phrase' => 'Okay ka lang?', 'video_path' => 'signs/phrases/okay ka lang, are you okay.mp4'],
                ['phrase' => 'Are you okay?', 'video_path' => 'signs/phrases/okay ka lang, are you okay.mp4'],
                ['phrase' => 'Okay lang ako', 'video_path' => 'signs/phrases/okay lang ako im okay.mp4'],
                ['phrase' => 'I\'m okay', 'video_path' => 'signs/phrases/okay lang ako im okay.mp4'],




                // Add more phrases as needed
            ];

            // Insert phrases into the database
            foreach ($phrases as $phrase) {
                Phrase::create([
                    'phrase' => $phrase['phrase'],
                    'video_path' => $phrase['video_path'],
                ]);
            }
    }
}
